services:
  kafka_manager:
    class: KafkaBundle\Manager\KafkaManager
    lazy: true
    arguments:
      - '@logger'
      - false
    tags:
      - { name: monolog.logger, channel: kafka }

  kafka_consumer_command:
    class: KafkaBundle\Command\ConsumerCommand
    arguments:
      - '@kafka_manager'
    tags: [ console.command ]
